services:
  servermonitoringandnotificationsystem:
    image: ${DOCKER_REGISTRY-}servermonitoringandnotificationsystem
    build:
      context: .
      dockerfile: ServerMonitoringAndNotificationSystem/Dockerfile
    environment:
      - RABBITMQ_HOSTNAME=rabbitmq
      - SERVER_IDENTIFIER=linux1
      - SAMPLING_INTERVAL_SECONDS=60
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo_data:/data/db

volumes:
  rabbitmq_data:
  mongo_data: